"""LucidFlow dashboard -- Drift Status.

Reads the saved per-batch PSI/KS report from Phase 4, Task 2
(src/lucidflow/drift/last_check_results.json) -- generated by
`python -m lucidflow.drift.build_batches`. Nothing here recomputes PSI/KS.
"""

import pandas as pd
import streamlit as st
from data_access import get_drift_status

st.set_page_config(page_title="Drift Status — LucidFlow", page_icon="📈", layout="wide")
st.title("Drift Status")

st.warning(
    "**Grounding note**: `companies.csv` is one static snapshot with no timestamp column, "
    "so there is no real longitudinal drift to detect. The three batches below are built from "
    "the same underlying data with a documented *synthetic* shift injected at two magnitudes "
    "-- this demonstrates the PSI/KS detector fires correctly on the shift types it's designed "
    "to catch, but it does **not** validate real-world drift-detection performance. "
    "See `src/lucidflow/drift/README.md` for the full reasoning."
)

results = get_drift_status()
if results is None:
    st.info(
        "No saved drift check found. Generate one with "
        "`python -m lucidflow.drift.build_batches`."
    )
    st.stop()

SEVERITY_ORDER = {"none": 0, "moderate": 1, "significant": 2}
SEVERITY_COLOR = {"none": "🟢", "moderate": "🟡", "significant": "🔴"}

rows = []
for batch_label, report in results.items():
    rows.append(
        {
            "batch": batch_label,
            "magnitude_scale": report["magnitude_scale"],
            "company_size (PSI)": f"{SEVERITY_COLOR[report['company_size']['severity']]} {report['company_size']['severity']}",
            "state null-rate (PSI)": f"{SEVERITY_COLOR[report['state_null_rate']['severity']]} {report['state_null_rate']['severity']}",
            "description length (KS)": f"{SEVERITY_COLOR[report['description_len']['severity']]} {report['description_len']['severity']}",
            "any_flagged": report["any_flagged"],
        }
    )

df = pd.DataFrame(rows).sort_values("magnitude_scale")
st.dataframe(df, hide_index=True, width="stretch")

st.divider()
st.subheader("Raw values")
for batch_label, report in sorted(results.items(), key=lambda kv: kv[1]["magnitude_scale"]):
    with st.expander(f"Batch {batch_label} (magnitude_scale={report['magnitude_scale']})"):
        col1, col2, col3 = st.columns(3)
        col1.metric("company_size PSI", f"{report['company_size']['value']:.4f}")
        col2.metric("state null-rate PSI", f"{report['state_null_rate']['value']:.4f}")
        col3.metric(
            "description length KS p-value",
            f"{report['description_len']['p_value']:.6f}",
        )
